export type {
    BoundedHealthCount,
    BuiltInPermissionAction,
    PermissionAction,
    PermissionCoreHealth,
    PermissionCoreLifecycle,
    PermissionCoreOptions,
    PermissionRuleAction,
    PermissionScope,
    PermissionSemanticCacheOptions,
    PermissionSubject,
    PolicyContext,
    PolicyScalar,
    PolicyValue,
    ResourceSchemeDefinition,
    ResourceSchemeProbe,
} from "./foundation";

export type {
    AuditLookupDetails,
    CapacityRiskAckRequiredDetails,
    CoreCloseTimeoutDetails,
    DatabaseFailureDetails,
    DataValueUnsupportedDetails,
    LimitExceededDetails,
    PermissionCoreErrorCode,
    PermissionCoreErrorDetails,
    PersistedStateInvalidDetails,
    PreviewRequiredDetails,
    ReconcileSupersededDetails,
    RevisionConflictDetails,
    SchemaMismatchDetails,
    ValidationErrorDetails,
} from "./errors";

export type {
    DynamicRowCondition,
    LiteralRowCondition,
    NonEmptyReadonlyArray,
    PolicyConditionOutcome,
    RowCondition,
    RowOperator,
} from "./policy";

export type * from "./data";

export type {
    AuditPreviewExpectation,
    AuthorizationCapacityAssessment,
    AuthorizationPreviewExpectation,
    BatchMutationSummary,
    BoundedDetails,
    CountSample,
    CursorQuery,
    EffectiveCapacityUsage,
    EntityRevisionRef,
    ExpectedRevisionVector,
    ImpactPreview,
    ManagementConflict,
    ManagementWarning,
    MutationOptions,
    MutationResult,
    PageResult,
    PreviewExecutionOptions,
    PreviewOptions,
    RequiredRevisionOptions,
    RequiredRevisionVectorOptions,
    ResponseDetailBudget,
    RevisionVector,
    ScopedMutationDefaults,
    SubjectRuntimeResult,
    VersionedResult,
} from "./management";

export type {
    EffectivePermissionSnapshot,
    EffectiveResourcePattern,
    EffectiveRoleRules,
    EffectiveRuleEntry,
    EffectiveUserRoleEntry,
    EntityStatus,
    ManualRuleChange,
    ManualRuleChangePlan,
    ManualRuleChangeResult,
    ManualRuleInput,
    ManualRuleSelector,
    MenuRuleSourceState,
    PermissionActionEvaluation,
    PermissionDecisionReason,
    PermissionDecisionTrace,
    PermissionExplanation,
    PermissionRuleInput,
    PermissionRuleView,
    Role,
    RoleAccessUpdateInput,
    RoleAccessUpdatePlan,
    RoleAuthorizationSnapshot,
    RoleChainEntry,
    RoleCreateInput,
    RoleManager,
    RoleRemovalImpact,
    RoleRuleReplacePlan,
    RoleUpdateInput,
    RuleConflict,
    RuleSourceView,
    ScopedPermissionContext,
    SourceAvailability,
    SourceDrift,
    SourceIntegrity,
    SubjectEffectiveRoleEntry,
    SubjectEffectiveRuleEntry,
    SubjectPermissionContext,
    SubjectRoleAuthorizationSnapshot,
    SubjectRuleConflict,
    UserEffectiveRoles,
    UserRoleBindingSet,
    UserRoleManager,
} from "./rbac";

export type * from "./menu";
